# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 03:46
from __future__ import unicode_literals

import SquareVeg.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SquareVeg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=SquareVeg.models.image_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SquareVeg.Product')),
            ],
        ),
    ]
