# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquareVeg', '0003_auto_20160823_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=10),
        ),
    ]
