# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquareVeg', '0004_auto_20160825_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalquantity',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=50),
        ),
    ]
