# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquareVeg', '0005_cart_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalquantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
